CREATE TABLE TB_PARTICIPANTE(
  ID_PARTICIPANTE INT CONSTRAINT PK_TB_PARTICIPANTE PRIMARY KEY,
  NM_PRIMEIRO VARCHAR(30) NOT NULL,
  NM_MEIO VARCHAR(30),
  NM_ULTIMO VARCHAR(30) NOT NULL,
  CD_CPF_PARTICIPANTE CHAR(11) CONSTRAINT UK_TB_PARTICIPANTE_CPF UNIQUE,
  DT_NASCIMENTO DATE,
  DS_ENDERECO VARCHAR(150),
  TP_GENERO CHAR(1), -- SENDO M-MASCULINO, F-MENININO, O-OUTRO
  TP_PARTICIPACAO CHAR(1), -- SENDO O-OUVINTE, M-MONITOR, I-INSTRUTOR
  CD_MATRICULA VARCHAR(9) CONSTRAINT UK_TB_PARTICIPANTE_MATRICULA UNIQUE,
  NM_INSTITUICAO VARCHAR(30)
);

CREATE TABLE TB_ATIVIDADE (
  ID_ATIVIDADE INT CONSTRAINT PK_TB_ATIVIDADE PRIMARY KEY,
  DT_ATIVIDADE DATE NOT NULL,
  HR_ATIVIDADE TIME NOT NULL,
  DS_LOCAL VARCHAR(150) NOT NULL,
  TP_ATIVIDADE CHAR(1) NOT NULL, -- SENDO E-EVENTO, P-PALESTRA, W-WORKSHOP, C-CURSOS, O-OUTROS
  NM_AREA_ESTUDO VARCHAR(30) NOT NULL,
  NM_ATIVIDADE VARCHAR(150) NOT NULL,
  CARGA_HORARIA INT NOT NULL,
  DS_ATIVIDADE VARCHAR(400) NOT NULL,
  DS_RELATORIO VARCHAR(400)
);

CREATE TABLE RL_PARTICIPA (
  ID_PARTICIPANTE INT NOT NULL,
  ID_ATIVIDADE INT NOT NULL,
  IS_CERTIFICADO CHAR(1) NOT NULL,
  DS_FEEDBACK VARCHAR(400),
  CONSTRAINT PK_RL_PARTICIPA PRIMARY KEY (ID_PARTICIPANTE, ID_ATIVIDADE),
  CONSTRAINT FK_RL_PARTICIPA_TB_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE) REFERENCES TB_PARTICIPANTE(ID_PARTICIPANTE),
  CONSTRAINT FK_RL_PARTICIPA_TB_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);

CREATE TABLE TB_PARCEIRO (
  ID_PARCEIRO INT CONSTRAINT PK_TB_PARCEIRO PRIMARY KEY,
  NM_PRIMEIRO VARCHAR(30) NOT NULL,
  NM_MEIO VARCHAR(30),
  NM_ULTIMO VARCHAR(30) NOT NULL,
  CD_CPF_REPRESENTANTE VARCHAR(11) CONSTRAINT UK_TB_PARCEIRO_CPF UNIQUE,
  NM_EMPRESA VARCHAR(150) NOT NULL,
  TP_CATEGORIA CHAR(1) NOT NULL, -- SENDO F-FINANCEIRO, P-PALESTRANTE, M-MATERIAL, O-OUTRO
  ID_ATIVIDADE INT NOT NULL,
  CONSTRAINT FK_TB_PARCEIRO_TB_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE) REFERENCES TB_ATIVIDADE(ID_ATIVIDADE)
);